[build]
  base = "/"
  publish = "public"
  command = "yarn build"

[build.environment]
  NODE_VERSION = "20"

[functions]
  directory = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-gatsby"
